### ISSUE TITLE
Why does this repo exist?

### ISSUE THREAD

**Issue by chrisant996** [chrisant996/readline_win32_sample#1]
This repo was created in response to https://github.com/chrisant996/clink/issues/377, to demonstrate in a simple (as much as possible) sample how to use the [Readline](https://tiswww.case.edu/php/chet/readline/rltop.html) library from a Windows console application.

**Comment by kirkw** [comment]
Yeah, NO longer declaring my own stuff!

I will review your project.

The big issue is that rl_instream is not initialized (it's -1).  There could be more issues, but will review your code.

THANK YOU...
