### ISSUE TITLE
Okay compile errors, and I cannot navigate "readline @ xxxx" folder on github?

### ISSUE THREAD

**Issue by kirkw** [chrisant996/readline_win32_sample#3]
@chrisant996 Okay, I did the premake...
it complains:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'readline/rldefs.h': No such file or directory	c_sample	C:\readline_win32_sample-main\c_sample.c	9	
Error	C1083	Cannot open include file: 'rldefs.h': No such file or directory	compat	C:\readline_win32_sample-main\compat\termcap.c	8	
Error	C1083	Cannot open include file: 'rlmbutil.h': No such file or directory	compat	C:\readline_win32_sample-main\compat\readline_glue.c	2	

Interesting. the ZIP file has an empty readline folder!

**Comment by kirkw** [comment]
@chrisant996 this is what I see, and I cannot click on that folder.
You might want to double check that it did not crosslink with your other readline.  Strange name...

![image](https://user-images.githubusercontent.com/10579315/203208641-55b583e1-23f8-4192-a555-a7ead30da903.png)

**Comment by chrisant996** [comment]
> @chrisant996 this is what I see, and I cannot click on that folder.
> You might want to double check that it did not crosslink with your other readline.  Strange name...
> 
> ![image](https://user-images.githubusercontent.com/10579315/203208641-55b583e1-23f8-4192-a555-a7ead30da903.png)
> 

Oh you tried to just copy files from a .zip file.

It's a git submodule, but you're not using git to access it, so you don't get the files.

Can you instead use `git clone` with the repo I shared?

(The "strange name" is actually a name "readline" and the associated commit hash for that submodule.)
